export default {
  accNotFound: 'accessory not found',
  accNotReady: 'cannot currently be controlled, see plugin startup logs for any error',
  addInfo: 'additional info',
  airDryingFail: 'sending air drying update failed as',
  canvasMissing: 'The optional canvas module is not built on this system, so map images cannot be processed. This does not affect any HomeKit functionality',
  cfgDef: 'is not a valid number so using default of',
  cfgDup: 'will be ignored since another entry with this ID already exists',
  cfgIgn: 'is not configured correctly so ignoring',
  cfgIgnItem: 'has an invalid entry which will be ignored',
  cfgItem: 'Config entry',
  cfgLow: 'is set too low so increasing to',
  cfgHigh: 'is set too high so reducing to',
  cfgRmv: 'is unused and can be removed',
  cfgQts: 'should not have quotes around its entry',
  chargeFail: 'sending charge update failed as',
  cleanFail: 'sending clean update failed as',
  cleaning: 'cleaning',
  characteristicsReset: 'characteristic values reset to 0',
  commandForArea: 'Command for predefined area',
  commandSent: 'command was sent',
  complete: '✓ Setup complete',
  curAirDrying: 'current air drying state',
  curArea: 'current predefined area',
  curBatt: 'current battery',
  curCharging: 'current charging state',
  curCleaning: 'current cleaning state',
  curSpeed: 'current cleaning speed',
  curTrueDetect: 'current true detection state',
  devAdd: 'has been added to Homebridge',
  deviceCount: acc => `device(s) found in your ${acc} account`,
  deviceListFail: 'could not retrieve devices from the cloud',
  devInit: 'initialised with id',
  devConfIdsAre: 'The device ids on your account are',
  devConfNoMatch: 'These device ids in your config match nothing on your account, so their settings are being ignored:',
  devInitOpts: 'initialising with options',
  devNotAdd: 'could not be added to Homebridge as',
  devNotConf: 'could not be configured as',
  devNotInit: 'could not be initialised as',
  devNotRef: 'could not be refreshed as',
  devNotRemove: 'could not be removed from Homebridge as',
  devRemove: 'has been removed from Homebridge',
  disabling: 'Disabling plugin',
  ecovacsLibVersion: 'Using ecovacs-deebot library',
  errNotInit: 'device has not initialised device yet',
  errNotReady: 'device is not ready to accept commands',
  hbVersionFail: 'Your version of Homebridge is too low - please update to v1.6',
  inAirFail: 'receiving air drying update failed as',
  inBattFail: 'receiving battery update failed as',
  inChgFail: 'receiving charge update failed as',
  inClnFail: 'receiving clean update failed as',
  inErrFail: 'receiving error update failed as',
  inSpdFail: 'receiving speed update failed as',
  inTrDFail: 'receiving true detect update failed as',
  initialised: 'Plugin initialised. Setting up accessories...',
  initialising: 'Initialising plugin',
  inMsgFail: 'receiving message update failed as',
  inRdyFail: 'receiving ready update failed as',
  invalidCCode: 'Invalid country code',
  invalidPassword: 'Invalid password',
  invalidUsername: 'Invalid username',
  loginBorrowed: 'Logged in using the newer version of the ecovacs-deebot library, as Ecovacs no longer accepts logins from the stable version for this account. Devices continue to run on the stable version as normal',
  lowBattMsg: 'Device has low battery - ',
  missingCreds: 'credentials missing from config',
  noCommandForArea: 'returning no command for predefined area',
  noTypeForArea: 'returning no type for predefined area',
  oldCommandFound: 'Old command (<= release 5.1.0) found for predefined area',
  pluginNotConf: 'Plugin has not been configured',
  receiveCmd: 'receiving update',
  repOffline: 'has been reported [offline]',
  repOnline: 'has been reported [online]',
  returning: 'returning',
  returningAsValueNull: 'returning as value === 0',
  sendCmd: 'sending update',
  sentErr: 'sent error',
  sentMsg: 'sent message',
  skippingValue: 'skipping old value as new value noticed',
  sessionCached: 'Reusing the saved Ecovacs login session from a previous start',
  sessionRenewed: 'The Ecovacs login session has been renewed before its expiry',
  sessionRenewFail: 'Could not renew the Ecovacs login session in the background, the current session continues:',
  sessionStale: 'The saved Ecovacs login session was not accepted, logging in freshly',
  speedFail: 'sending speed update failed as',
  stop: 'stop',
  storageSetupErr: 'Session storage could not be set up:',
  typeForArea: 'Type for predefined area',
  unknownCommandTypeForArea: 'Unknown command type for predefined area',
  verifyCodeInvalid: 'The configured verification code was invalid or expired, so Ecovacs has emailed a new code to your account address (check your spam folder; the code expires after 24 hours). Enter the new code into the plugin\'s "Verification Code" setting and restart Homebridge',
  verifyCodeSent: 'Ecovacs requires this device to be verified, so a verification code has been emailed to your account address. Look for an email from "ECOVACS Robotics" (noreply@support.ecovacs.com) about a login on a new mobile device — that device is this plugin — and check your spam folder if it does not appear. The code expires after 24 hours. Enter it into the plugin\'s "Verification Code" setting and restart Homebridge',
  verifyStableFail: 'The Ecovacs login completed but did not provide a usable session. Please open a support request on GitHub so this can be investigated',
  verifySuccess: 'Device verification was successful. You can now remove the code from the plugin\'s "Verification Code" setting',
}
